apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: assetx
build:
  local:
    push: false
  artifacts:
    - image: assetx-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: assetx-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {} 