export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Account Types
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAIL = 'ADD_ACCOUNT_FAIL';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const CLEAR_CURRENT_ACCOUNT = 'CLEAR_CURRENT_ACCOUNT';
export const SET_ACCOUNT_LOADING = 'SET_ACCOUNT_LOADING';

// Transaction Types
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL = 'ADD_TRANSACTION_FAIL';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAIL = 'UPDATE_TRANSACTION_FAIL';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';
export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';

// Dashboard Types
export const GET_DASHBOARD_SUMMARY_SUCCESS = 'GET_DASHBOARD_SUMMARY_SUCCESS';
export const GET_DASHBOARD_SUMMARY_FAIL = 'GET_DASHBOARD_SUMMARY_FAIL';
export const GET_MONTHLY_CATEGORY_SUMMARY_SUCCESS = 'GET_MONTHLY_CATEGORY_SUMMARY_SUCCESS';
export const GET_MONTHLY_CATEGORY_SUMMARY_FAIL = 'GET_MONTHLY_CATEGORY_SUMMARY_FAIL';
export const GET_ASSET_DISTRIBUTION_SUCCESS = 'GET_ASSET_DISTRIBUTION_SUCCESS';
export const GET_ASSET_DISTRIBUTION_FAIL = 'GET_ASSET_DISTRIBUTION_FAIL';
export const GET_NET_WORTH_GROWTH_SUCCESS = 'GET_NET_WORTH_GROWTH_SUCCESS';
export const GET_NET_WORTH_GROWTH_FAIL = 'GET_NET_WORTH_GROWTH_FAIL';
export const SET_DASHBOARD_LOADING = 'SET_DASHBOARD_LOADING';

// Investment Types
export const GET_INVESTMENTS_SUCCESS = 'GET_INVESTMENTS_SUCCESS';
export const GET_INVESTMENTS_FAIL = 'GET_INVESTMENTS_FAIL';
export const ADD_INVESTMENT_SUCCESS = 'ADD_INVESTMENT_SUCCESS';
export const ADD_INVESTMENT_FAIL = 'ADD_INVESTMENT_FAIL';
export const UPDATE_INVESTMENT_SUCCESS = 'UPDATE_INVESTMENT_SUCCESS';
export const UPDATE_INVESTMENT_FAIL = 'UPDATE_INVESTMENT_FAIL';
export const DELETE_INVESTMENT_SUCCESS = 'DELETE_INVESTMENT_SUCCESS';
export const DELETE_INVESTMENT_FAIL = 'DELETE_INVESTMENT_FAIL';
export const SET_CURRENT_INVESTMENT = 'SET_CURRENT_INVESTMENT';
export const CLEAR_CURRENT_INVESTMENT = 'CLEAR_CURRENT_INVESTMENT';
export const SET_INVESTMENT_LOADING = 'SET_INVESTMENT_LOADING';
export const INVESTMENT_ERROR = 'INVESTMENT_ERROR';

// Trade Types
export const GET_TRADES_SUCCESS = 'GET_TRADES_SUCCESS';
export const GET_TRADES_FAIL = 'GET_TRADES_FAIL';
export const ADD_TRADE_SUCCESS = 'ADD_TRADE_SUCCESS';
export const ADD_TRADE_FAIL = 'ADD_TRADE_FAIL';
export const UPDATE_TRADE_SUCCESS = 'UPDATE_TRADE_SUCCESS';
export const UPDATE_TRADE_FAIL = 'UPDATE_TRADE_FAIL';
export const DELETE_TRADE_SUCCESS = 'DELETE_TRADE_SUCCESS';
export const DELETE_TRADE_FAIL = 'DELETE_TRADE_FAIL';
export const SET_CURRENT_TRADE = 'SET_CURRENT_TRADE';
export const CLEAR_CURRENT_TRADE = 'CLEAR_CURRENT_TRADE';
export const SET_TRADE_LOADING = 'SET_TRADE_LOADING';
export const TRADE_ERROR = 'TRADE_ERROR';
export const CLEAR_TRADES = 'CLEAR_TRADES'; 