# k8s/backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # 注意：這裡的 KEY 必須跟您 .env 檔案中的 KEY 一致
  # 這裡的 VALUE 則是您上個步驟中 Base64 編碼後的結果
  MONGO_URI: bW9uZ29kYjovL2FkbWluOjAxMDYwNkAxMC4wLjIuMjI6MjcwMTcvYXNzZXRYP2F1dGhTb3VyY2U9YWRtaW4=
  API_KEY: NGU0ZTZkZGNhZDhkZTEzYmU1OTRlMDk1YjhkOWY1OTcyOGI3NzNiM2I0MDlmMWQ2YmI0MzQwMDA5OGIzMjU3NGI4N2ZkNGViYWEwMTg2ZGZkYjczOTc1ZGYzOTA0YmM0MTk3MWJjYjI1MzY4NDVjZTUzZjA4ODgyMTE4MjcxMTRiNTY5MzU1ZGUwZmUzNDUzM2MzOGJhYjM0YmUzY2UzNGZlOTk5MzU5MmEyYmI3YzcwMDVhMzg1NzlkY2UzZDZlNWZkZWM0MzA4M2EyZDRjOGJhMjRkODRkOTgyYjg3N2JiOGNhMmVjMDBjNjg3ZDk4NmFjMjk5MDYzNjM3ODI3M2Y3MjgwMGUyNDg3MmI2MzEzNTNlNTg3YjQyNjI5MmQxM2E0Mjk5ODdjY2ViYzdkYmE0NDZjODUyYzEwOTUxMTgyZWJjZjFhNmU4ZTk0Y2JmMjk1NmUyNGRmODEzNWZiYzA3YjNhMTBkYzc0OWYxMzg3ZGY5ZTdlODg2OTBiYjU3NTM4ZDFmODQwNWNlMTczNmFmMWNkZTIwYzI5NGE0N2NiYmQzY2IyZDQyODk2OWJkNGZiNDJmODFlYzYzNzEwYzQxMWNiNjc2ZDM4ODU3NmRkOGFiYTk1MmZlN2RlZGFhNjJiNzI5MTQwNmQ3OWExNTIwMDJhMjE2ODYwOWEyODk=
  PORT: NTAwMA==