export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';
export const SET_CURRENT_TRANSACTION = 'SET_CURRENT_TRANSACTION';
export const CLEAR_CURRENT_TRANSACTION = 'CLEAR_CURRENT_TRANSACTION'; 